import type { UserRole } from "@prisma/client";

/** Granular permissions for RBAC */
export const PERMISSIONS = {
  "account:read": "View own account",
  "account:write": "Update own profile",
  "account:delete": "Request account deletion",
  "orders:read": "View orders",
  "orders:write": "Place and manage orders",
  "admin:ecommerce:read": "View e-commerce payment dashboard",
  "admin:ecommerce:write": "Manage e-commerce orders and payments",
  "subscriptions:read": "View subscriptions",
  "subscriptions:write": "Manage subscriptions",
  "admin:farm:read": "View farm dashboard",
  "admin:farm:write": "Manage farm operations",
  "admin:security:read": "View security dashboard",
  "admin:security:write": "Manage security settings",
  "admin:users:read": "View users",
  "admin:users:write": "Manage users and roles",
  "delivery:read": "View delivery assignments",
  "delivery:write": "Update delivery status",
  "mobile:customer": "Customer mobile app",
  "mobile:delivery": "Delivery boy mobile app",
  "mobile:farm": "Farm manager mobile app",
  "mobile:vet": "Veterinarian mobile app",
  "mobile:owner": "Owner mobile dashboard",
  "notifications:read": "View own notifications",
  "admin:notifications:read": "View notification admin dashboard",
  "admin:notifications:write": "Send broadcasts and manage templates",
  "workflows:read": "View own workflow requests",
  "workflows:write": "Submit approval requests",
  "workflows:approve": "Approve or reject workflow steps",
  "admin:workflows:read": "View workflow admin dashboard",
  "admin:workflows:write": "Build and manage workflow definitions",
  "documents:read": "View and download documents",
  "documents:write": "Upload and manage documents",
  "documents:sign": "Digitally sign documents",
  "admin:documents:read": "View document admin dashboard",
  "admin:documents:write": "Manage folders and all documents",
  "admin:integrations:read": "View integrations dashboard",
  "admin:integrations:write": "Connect and configure integrations",
  "crm:read": "View CRM records assigned or public",
  "crm:write": "Manage leads, opportunities, and quotations",
  "crm:support": "Create and view own support tickets",
  "admin:crm:read": "View CRM admin dashboard",
  "admin:crm:write": "Manage full CRM pipeline and campaigns",
  "fleet:read": "View fleet vehicles and trips",
  "fleet:write": "Log fuel, maintenance, and GPS",
  "admin:fleet:read": "View fleet admin dashboard",
  "admin:fleet:write": "Manage vehicles, drivers, and routes",
  "processing:read": "View milk processing batches and recipes",
  "processing:write": "Run batches, QC, and packaging",
  "admin:processing:read": "View processing admin dashboard",
  "admin:processing:write": "Manage recipes and production planning",
  "retail:read": "View POS bills and scan products",
  "retail:write": "Create bills, returns, and offline sync",
  "admin:retail:read": "View retail admin dashboard",
  "admin:retail:write": "Manage terminals and loyalty",
  "ai:read": "View AI insights and run analysis",
  "ai:write": "Use voice, WhatsApp, and agents",
  "admin:ai:read": "View AI platform dashboard",
  "admin:ai:write": "Configure agents and run all modules",
  "saas:read": "View marketplace and regional settings",
  "saas:write": "Install apps and configure tax/shipping",
  "admin:saas:read": "View SaaS platform admin",
  "admin:saas:write": "Manage tenants, partners, and marketplace",
  "partner:read": "View partner portal",
  "reseller:read": "View reseller portal",
} as const;

export type Permission = keyof typeof PERMISSIONS;

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  CUSTOMER: [
    "account:read",
    "account:write",
    "account:delete",
    "orders:read",
    "orders:write",
    "subscriptions:read",
    "subscriptions:write",
    "mobile:customer",
    "notifications:read",
    "workflows:read",
    "workflows:write",
    "documents:read",
    "crm:support",
  ],
  DELIVERY: [
    "account:read",
    "delivery:read",
    "delivery:write",
    "orders:read",
    "mobile:delivery",
    "notifications:read",
    "fleet:read",
    "fleet:write",
  ],
  VETERINARIAN: [
    "account:read",
    "admin:farm:read",
    "mobile:vet",
    "workflows:read",
    "workflows:write",
  ],
  ACCOUNTANT: [
    "account:read",
    "admin:farm:read",
    "orders:read",
    "workflows:read",
    "workflows:write",
    "workflows:approve",
    "admin:workflows:read",
    "documents:read",
    "documents:write",
    "documents:sign",
    "admin:documents:read",
    "admin:integrations:read",
    "crm:read",
    "crm:write",
    "admin:crm:read",
    "retail:read",
    "retail:write",
    "admin:retail:read",
    "admin:ecommerce:read",
    "ai:read",
    "ai:write",
    "admin:ai:read",
    "saas:read",
  ],
  IOT_OPERATOR: [
    "account:read",
    "admin:farm:read",
    "admin:farm:write",
    "documents:read",
    "fleet:read",
    "processing:read",
    "processing:write",
    "retail:read",
    "retail:write",
  ],
  FARM_MANAGER: [
    "account:read",
    "admin:farm:read",
    "admin:farm:write",
    "admin:security:read",
    "admin:notifications:read",
    "orders:read",
    "mobile:farm",
    "notifications:read",
    "workflows:read",
    "workflows:write",
    "workflows:approve",
    "admin:workflows:read",
    "documents:read",
    "documents:write",
    "documents:sign",
    "admin:documents:read",
    "admin:documents:write",
    "crm:read",
    "crm:write",
    "crm:support",
    "admin:crm:read",
    "admin:crm:write",
    "fleet:read",
    "fleet:write",
    "admin:fleet:read",
    "admin:fleet:write",
    "processing:read",
    "processing:write",
    "admin:processing:read",
    "admin:processing:write",
    "retail:read",
    "retail:write",
    "admin:retail:read",
    "admin:retail:write",
    "admin:ecommerce:read",
    "ai:read",
    "ai:write",
    "admin:ai:read",
    "admin:ai:write",
    "saas:read",
    "saas:write",
    "admin:saas:read",
    "admin:saas:write",
  ],
  ADMIN: Object.keys(PERMISSIONS) as Permission[],
  OWNER: Object.keys(PERMISSIONS) as Permission[],
};

export function getRolePermissions(role: string): Permission[] {
  return ROLE_PERMISSIONS[role as UserRole] ?? ROLE_PERMISSIONS.CUSTOMER;
}

export function hasPermission(role: string, permission: Permission): boolean {
  return getRolePermissions(role).includes(permission);
}

export function hasAnyPermission(role: string, permissions: Permission[]): boolean {
  const granted = getRolePermissions(role);
  return permissions.some((p) => granted.includes(p));
}

export function isSecurityAdmin(role: string): boolean {
  return hasPermission(role, "admin:security:read");
}
