apiVersion: v1
kind: ConfigMap
metadata:
  name: ssd-app-config
  namespace: shree-shyam
data:
  APP_ENV: "production"
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  STORAGE_PROVIDER: "r2"
  MQTT_BRIDGE_ENABLED: "false"
  OPENAI_MODEL: "gpt-4o-mini"
