apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssd-app
  namespace: shree-shyam
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
    - hosts:
        - kunwardairy.com
        - www.kunwardairy.com
      secretName: ssd-tls
  rules:
    - host: kunwardairy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssd-app
                port:
                  number: 80
    - host: www.kunwardairy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssd-app
                port:
                  number: 80
